# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
    ]
