# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Bank'),
        ),
    ]
